# Generated by Django 3.2.18 on 2023-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlist',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetlist',
            name='value',
            field=models.FloatField(max_length=20),
        ),
    ]
