# Generated by Django 3.2.18 on 2023-04-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0002_auto_20230430_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetlist',
            name='value',
        ),
        migrations.AddField(
            model_name='budgetlist',
            name='income',
            field=models.FloatField(default=1230, max_length=20),
        ),
        migrations.AddField(
            model_name='budgetlist',
            name='names',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='budgetlist',
            name='values',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='budgetlist',
            name='name',
            field=models.CharField(default='budgeting', max_length=20),
        ),
    ]
