# Generated by Django 3.2.18 on 2023-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0004_auto_20230501_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlist',
            name='values',
            field=models.CharField(max_length=200),
        ),
    ]
