# Generated by Django 3.2.18 on 2023-04-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0006_auto_20230501_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetlist',
            name='final_allocation',
        ),
    ]
