# Generated by Django 4.2.1 on 2023-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0007_remove_budgetlist_final_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=20)),
            ],
        ),
    ]
