# Generated by Django 4.2.1 on 2023-06-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0008_nativeitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NativeItems',
            new_name='NativeItem',
        ),
    ]
