# Generated by Django 4.2.1 on 2023-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0009_rename_nativeitems_nativeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='nativeitem',
            name='itemtype',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
