# Generated by Django 4.2.1 on 2023-06-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0010_nativeitem_itemtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nativeitem',
            old_name='itemtype',
            new_name='item_type',
        ),
    ]
