# Generated by Django 4.2.1 on 2023-06-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0011_rename_itemtype_nativeitem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='nativeitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefProg.typedefinition'),
        ),
    ]
