# Generated by Django 4.2.1 on 2023-06-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0012_typedefinition_alter_nativeitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativeitem',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
