# Generated by Django 4.2.1 on 2023-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0013_alter_nativeitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativeitem',
            name='unit',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
