# Generated by Django 4.2.1 on 2023-06-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0014_alter_nativeitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativeitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
