# Generated by Django 4.2.1 on 2023-06-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0015_alter_nativeitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nativeitem',
            name='item_subtype',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
