# Generated by Django 4.2.1 on 2023-06-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0018_computationparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computationparam',
            name='items',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='computationparam',
            name='types',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
