# Generated by Django 4.2.1 on 2023-06-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefProg', '0019_alter_computationparam_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computationparam',
            old_name='items',
            new_name='hierarchy_field',
        ),
        migrations.RemoveField(
            model_name='computationparam',
            name='types',
        ),
    ]
